// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGAsiV9ZtKZsfFjk0GfT1BANpvvbOfdnQ',
    appId: '1:260489373070:android:5294368fbaadd07c15b0df',
    messagingSenderId: '260489373070',
    projectId: 'capstonedg-747c1',
    storageBucket: 'capstonedg-747c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDggceEYhKfqpJtaCg8md49pzHRCAJN8OI',
    appId: '1:260489373070:ios:3051954ec47eefe415b0df',
    messagingSenderId: '260489373070',
    projectId: 'capstonedg-747c1',
    storageBucket: 'capstonedg-747c1.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4gr9Kpq8JVtVLtC7an10LsAZOABScf8',
    appId: '1:260489373070:web:5fbc07bac76ee4f915b0df',
    messagingSenderId: '260489373070',
    projectId: 'capstonedg-747c1',
    authDomain: 'capstonedg-747c1.firebaseapp.com',
    storageBucket: 'capstonedg-747c1.appspot.com',
    measurementId: 'G-8SXBPH8S6P',
  );

}